import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:5173/learning-oe-solidjs/menu');
    await page.getByRole('button', { name: 'Edit Courses' }).click();
    await page.getByRole('button', { name: '✨' }).click();
    await page.getByRole('heading', { name: 'Course:' }).locator('q').click();
    await page.getByRole('heading', { name: 'Course:' }).locator('span').fill('Playwright Course');
    await page.locator('h3').click();
    await page.locator('h3 span').fill('Playwright course description');
    await page.locator('h3 span').press('Tab');
    await page.getByRole('button', { name: '' }).click();
    await page.getByRole('button', { name: '➕︎' }).click();
    await page.getByRole('button', { name: 'writing', exact: true }).click();
    await page.getByRole('textbox', { name: 'Option: enter a question' }).click();
    await page.getByRole('textbox', { name: 'Option: enter a question' }).press('Home');
    await page.getByRole('textbox', { name: 'Option: enter a question' }).fill('A Question');
    await page.getByRole('textbox', { name: 'Enter answer' }).click();
    await page.getByRole('textbox', { name: 'Enter answer' }).press('Home');
    await page.getByRole('textbox', { name: 'Enter answer' }).fill('An Answer');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.locator('.card-overlay').click();
    await page.getByRole('heading', { name: 'Editing Writing Card ✕' }).dblclick();
    await page.getByRole('button', { name: '✕' }).click();
    await page.getByText('A Lesson', { exact: true }).click();
    await page.getByText('A Lesson', { exact: true }).press('End');
    await page.getByText('A Lesson', { exact: true }).fill('A Lesson Title');
    await page.getByText('A lesson description').click();
    await page.getByText('A lesson description').dblclick();
    await page.getByText('A lesson description').press('ArrowRight');
    await page.getByText('A lesson description').fill('A lesson description gere');
    await page.getByText('A lesson description').press('ControlOrMeta+Shift+ArrowLeft');
    await page.getByText('A lesson description gere').fill('A lesson description here');
    await page.getByRole('button', { name: 'Toggle menu' }).click();
    await page.getByText('Custom Course').click();
    await page.getByRole('button', { name: 'A Lesson Title' }).click();
    await page.getByRole('button', { name: 'Begin' }).click();
    await page.getByRole('textbox', { name: 'enter_answer' }).click();
    await page.getByRole('textbox', { name: 'enter_answer' }).fill('An Answer');
    await page.getByRole('button', { name: 'action-button' }).click();
});